// import {
//   BookOpen,
//   Briefcase,
//   Calendar,
//   Code,
//   Dumbbell,
//   FileText,
//   Mail,
//   PenTool,
//   Receipt,
//   Rocket,
//   Users,
//   Video,
// } from 'lucide-react'

// import type { Task, TaskPriority } from './types/task.type'
// import { addDays } from './lib/dates'

// // Seed dates relative to "now" so Today / Overdue / Upcoming always read true.
// const base = new Date()

// export const TASKS: Task[] = [
//   {
//     id: 'k1',
//     title: 'Fix JWT claim mismatch',
//     category: 'cyan',
//     categoryLabel: 'Backend',
//     icon: Code,
//     due: addDays(base, -2),
//     time: '10:00',
//     status: 'in_progress',
//     priority: 'urgent',
//     notes:
//       'Align the claim (id ↔ userId) and role casing (CUSTOMER ↔ Customer) across the user, task and goal services. Blocks every authenticated request.',
//   },
//   {
//     id: 'k2',
//     title: 'Submit expense report',
//     category: 'cyan',
//     categoryLabel: 'Admin',
//     icon: Receipt,
//     due: addDays(base, -5),
//     status: 'done',
//     priority: 'low',
//   },
//   {
//     id: 'k3',
//     title: 'Reply to design feedback',
//     category: 'periwinkle',
//     categoryLabel: 'Design',
//     icon: Mail,
//     due: addDays(base, -1),
//     status: 'done',
//     priority: 'medium',
//   },
//   {
//     id: 'k4',
//     title: 'Review auth-service PR',
//     category: 'cyan',
//     categoryLabel: 'Work',
//     icon: Code,
//     due: addDays(base, 0),
//     time: '09:00',
//     status: 'done',
//     priority: 'medium',
//   },
//   {
//     id: 'k5',
//     title: 'Design review — Today dashboard',
//     category: 'periwinkle',
//     categoryLabel: 'Design',
//     icon: PenTool,
//     due: addDays(base, 0),
//     time: '11:30',
//     status: 'in_progress',
//     priority: 'high',
//     notes: 'Walk through the new dashboard layout and the summary-strip metrics.',
//   },
//   {
//     id: 'k6',
//     title: 'Workout — upper body',
//     category: 'lime',
//     categoryLabel: 'Health',
//     icon: Dumbbell,
//     due: addDays(base, 0),
//     time: '14:00',
//     status: 'todo',
//     priority: 'low',
//   },
//   {
//     id: 'k7',
//     title: 'Write Tasks screen spec',
//     category: 'cyan',
//     categoryLabel: 'Product',
//     icon: FileText,
//     due: addDays(base, 1),
//     status: 'todo',
//     priority: 'medium',
//     notes: 'List, Week and Month views; status + priority; reusable detail panel.',
//   },
//   {
//     id: 'k8',
//     title: 'Read: Refactoring UI, ch. 4',
//     category: 'periwinkle',
//     categoryLabel: 'Learning',
//     icon: BookOpen,
//     due: addDays(base, 2),
//     status: 'todo',
//     priority: 'low',
//   },
//   {
//     id: 'k9',
//     title: 'Plan Q3 goals',
//     category: 'cyan',
//     categoryLabel: 'Business',
//     icon: Briefcase,
//     due: addDays(base, 3),
//     status: 'todo',
//     priority: 'high',
//     notes: 'Draft the quarter objectives and key results.',
//   },
//   {
//     id: 'k10',
//     title: 'Record demo video',
//     category: 'periwinkle',
//     categoryLabel: 'Marketing',
//     icon: Video,
//     due: addDays(base, 4),
//     status: 'todo',
//     priority: 'medium',
//   },
//   {
//     id: 'k11',
//     title: 'Dentist appointment',
//     category: 'lime',
//     categoryLabel: 'Personal',
//     icon: Calendar,
//     due: addDays(base, 6),
//     time: '15:30',
//     status: 'todo',
//     priority: 'medium',
//   },
//   {
//     id: 'k12',
//     title: 'Team retro',
//     category: 'cyan',
//     categoryLabel: 'Work',
//     icon: Users,
//     due: addDays(base, 9),
//     time: '16:00',
//     status: 'todo',
//     priority: 'low',
//   },
//   {
//     id: 'k13',
//     title: 'Ship v0.2 release',
//     category: 'lime',
//     categoryLabel: 'Product',
//     icon: Rocket,
//     due: addDays(base, 14),
//     status: 'todo',
//     priority: 'high',
//     notes: 'Cut the release once Tasks lands.',
//   },
// ]

// export const PRIORITY_META: Record<TaskPriority, { label: string; dot: string }> = {
//   urgent: { label: 'Urgent', dot: 'bg-status-blocked' },
//   high: { label: 'High', dot: 'bg-status-warning' },
//   medium: { label: 'Medium', dot: 'bg-status-progress' },
//   low: { label: 'Low', dot: 'bg-status-muted' },
// }
